version: '3.1'

services:
  mongodb2:
    container_name: mongodb2
    image: mongo:4.4.4
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123

    expose:
      - 27017
    #ports:
    #  - 27017:27017
    volumes:
      -  mongodb2Volume:/data/db
    networks:
      - OfimaticaFinalNetwork

  golang:
    container_name: backend
    #image: diefre4k/backend:18
    image: malushita/backend-api:2
    ports:
      - 8001:8001
    networks:
      - OfimaticaFinalNetwork
    depends_on:
      - mongodb2
    restart: unless-stopped

volumes:
  mongodb2Volume:
#
networks:
  OfimaticaFinalNetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.50.0.0/16